CREATE TABLE chat_message (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender    VARCHAR(255),
    content   VARCHAR(1000),
    type      VARCHAR(20),
    timestamp TIMESTAMP
);
